FROM python:3.11-slim

RUN pip install mlflow psycopg2-binary

WORKDIR /app

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "postgresql://retainai_user:retainai_password@db:5432/retainai_db", "--default-artifact-root", "/ivs/my_folder/master/hk252/smart_system/smart_system_hk252/mlruns", "--serve-artifacts"]