FROM python:3.11-slim

RUN pip install mlflow psycopg2-binary

WORKDIR /app

EXPOSE 5000

COPY docker/entrypoint.mlflow.sh /entrypoint.sh
RUN sed -i 's/\r$//' /entrypoint.sh && chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]