FROM python:3.11-slim

RUN pip install mlflow psycopg2-binary
EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "postgresql://retainai_user:retainai_password@db:5432/retainai_db", "--default-artifact-root", "./mlruns"]
